version: "3.8"

services:
  server: # This can be any name you want
    image: node:14.15.1
    depends_on:
      - mongo # looks for a service defined in this compose file, with the exact name defined here (case-sensitive)
    ports:
      - "8443:8443" # Map local port 8080 to container port 8080
                    # Without this mapping, there is no way to connect to the container from our local network
    volumes:
      - server_logs:/var/logs/server
      - .:/applications/primetracking-server/
    working_dir: /applications/primetracking-server/
    command: "npm run start:dev"
    restart: on-failure


  mongo: # Whenever you need to connect to Mongodb from inside the container, make sure the IP host is the EXACT same as this
    # Ex: const connection = "mongodb://mongo:27017/mydb"; (instead of localhost:27017,
    # we say "mongo:27017" because the name of the service is defined as "mongo" here (case-sensitive)
    command: ['mongod', '--auth']
    image: mongo:4.4.2-bionic
    environment:
      MONGO_INITDB_DATABASE: primetracking
    ports:
      - "27017:27017"
    volumes:
      - ./config/init_db_scripts/:/docker-entrypoint-initdb.d/
      - ./config/mongod.conf:/etc/mongod.conf  # configure mongodb through a local config file
      - mongo_storage:/data/db  # allow mongodb to store data outside of the container so the data persists across container restarts
                                # by default, mongodb will read data from /data/db (inside the container)
                                # on our local machine, this will stored in whichever directory the path before the ":" points to
    restart: always


volumes:
  mongo_storage:
  server_logs: